### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by dasa** [cincheo/jsweet-quickstart#5]
I've followed the guide, but when I run `mvn generate-sources` I get 15 of these tsc errors:

```
2016-07-08 17:55:52.052 INFO  JSweetTranspiler:1081 - ../../.jsweet/candies/typings/src/typings/bundle.d.ts(2462,25): error TS2313: Constraint of a type parameter cannot reference any type parameter from the same type parameter list.
ERROR: constraint of a type parameter cannot reference any type parameter from the same type parameter list at ../../.jsweet/candies/typings/src/typings/bundle.d.ts(2462)
```

**Comment by renaudpawlak** [comment]
I think that you have hit this issue: https://github.com/cincheo/jsweet/issues/110.

It's because at this point, JSweet is not able to update tsc automatically. So, I think that to fix it, you need to go to your home directory and remove the ``.jsweet-node_modules`` directory. Then, JSweet should reinstall the latest version of TSC and everything should be fine again.

We should really do something about this issue but so far I am not sure what would be the best strategy.

**Comment by dasa** [comment]
That fixed it 👍
