### ISSUE TITLE
ERROR output:55 - namespace 'java.util' has no exported member 'Calendar'

### ISSUE THREAD

**Issue by epfromer** [cincheo/jsweet-quickstart#8]
Hi - I'm tinkering with jsweet and got the quickstart running without issue.  I then copied in a bunch of Java code from another project, running mvn generate-sources, and am trying to fix the errors.  I'm getting the following and wonder which libs to pull in?

ERROR output:55 - namespace 'java.util' has no exported member 'Calendar'
ERROR output:55 - namespace 'java.util' has no exported member 'SimpleTimeZone'
ERROR output:55 - property 'printf' does not exist on type 'PrintStream'

Thanks for any help.

**Comment by lgrignon** [comment]
Hi.
Porting a whole Java project to JSweet could be a hard job because JSweet doesn't support everything in the Java API. Using J4TS (https://github.com/j4ts/j4ts - Java runtime for Javascript) - that I think you use if you started from the quickstart - covers most of the Java API but some parts could be missing.
For instance, the Calendar class hasn't been implemented yet:
https://github.com/j4ts/j4ts/tree/master/src/main/java/java/util

Any chance you could contribute on this? Otherwise I recommend you to write a workaround using the Date class.

Same goes for the PrintStream.printf:
https://github.com/j4ts/j4ts/blob/64e3c6850d82694a0a75395293cc8f8e1c4c8f3b/src/main/java/java/io/PrintStream.java

but this latter is pretty easy to write differently :)

Please tell me if you need help

**Comment by epfromer** [comment]
Thanks Louis for the quick response - I'll look into the workarounds, and consider the contribution question.

**Comment by lgrignon** [comment]
@epfromer is this solved? Could you close this issue please?
